esphome: #Инициализация esphome
  name: esp-1 
  friendly_name: esp_1
  

esp8266: #Инициализация esp8266
  board: esp01_1m
  framework:
    version: 2.7.4

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "3LGOSZCnf+uYSwsNBMXAL0IjqkEqYE4EJBwutogiCPw="

ota: #Установка какого-то пароля =)
  password: "0f6a0d11966e4aec0ed7d9fdf79bebbc"

wifi: #Установка сети wifi
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-1 Fallback Hotspot"
    password: "xV25T3x3Ezov"

captive_portal:
  # Example configuration entry

i2c: #Инициализация портов i2c
  sda: GPIO5
  scl: GPIO4
sensor: #Инициализация датчиков
  - platform: bme280 #Указание платформы датчика
    temperature:
      name: "BME280 Temperature1" #Установка названия параметра температура
      oversampling: 16x #Установка частоты дискретизации
    pressure:
        name: "BME280 Pressure1" #Установка названия параметра давление
    humidity:
        name: "BME280 Humidity1" #Установка названия параметра влажность
    address: 0x76 #Установка адреса датчика
    update_interval: 10s #Установка частоты обновления
    
  - platform: bme280 #Указание платформы датчика
    temperature:
      name: "BME280 Temperature2" #Установка названия параметра температура
      oversampling: 16x #Установка частоты дискретизации
    pressure:
        name: "BME280 Pressure2" #Установка названия параметра давление"
    humidity:
        name: "BME280 Humidity2" #Установка названия параметра влажность
    address: 0x77 #Установка адреса датчика
    update_interval: 10s #Установка частоты обновления
    
  - platform: wifi_signal 
    name: "WiFi Signal dB" #Установка названия
    id: wifi_signal_db #Установка id
    update_interval: 20s #Установка частоты обновления
    entity_category: "diagnostic" #Установка категории "Диагностика"

  - platform: copy
    source_id: wifi_signal_db #Указание наследования 
    name: "WiFi Signal Percent" #Установка названия
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0); #Расчёт качества сигнала WiFi
    unit_of_measurement: "Signal %" #Установка еденицы измерения
    entity_category: "diagnostic" #Установка категории "Диагностика"

light: #Инициализация подсветки
  - platform: fastled_clockless #Указание платформы подсветки
    chipset: WS2812B #Указание чипсета
    pin: GPIO2 #Инициализация порта
    num_leds: 8 #Количество светодиодов
    rgb_order: GRB #Указание цветовой схемы
    name: "led1" #Установка названия
    effects: #Создание эффектов
      - addressable_color_wipe: 
          name: Red 
          colors:
            - red: 100% #Установка цвета на 100%
              green: 0% #Установка цвета на 0%
              blue: 0% #Установка цвета на 0%
              num_leds: 1 #Указание с каким количество светодиодов работать 
            - red: 0% #Установка цвета на 0%
              green: 0% #Установка цвета на 0%
              blue: 0% #Установка цвета на 0%
              num_leds: 1 #Указание с каким количество светодиодов работать
          add_led_interval: 100ms #Установка времени задержки
          reverse: False #Установка направления (реверса)
      - addressable_color_wipe:
          name: Green
          colors:
            - red: 0% #Установка цвета на 0%
              green: 100% #Установка цвета на 100%
              blue: 0% #Установка цвета на 0%
              num_leds: 1 #Указание с каким количество светодиодов работать
            - red: 0% #Установка цвета на 0%
              green: 0% #Установка цвета на 0%
              blue: 0% #Установка цвета на 0%
              num_leds: 1 #Указание с каким количество светодиодов работать
          add_led_interval: 100ms #Установка времени задержки
          reverse: False #Установка направления (реверса)
      - addressable_color_wipe:
          name: Blue
          colors:
            - red: 0% #Установка цвета на 0%
              green: 0% #Установка цвета на 0%
              blue: 100% #Установка  цвета на 100%
              num_leds: 1 #Указание с каким количество светодиодов работать
            - red: 0% #Установка цвета на 0%
              green: 0% #Установка цвета на 0%
              blue: 0% #Установка цвета на 0%
              num_leds: 1 #Указание с каким количество светодиодов работать
          add_led_interval: 100ms #Установка времени задержки
          reverse: False #Установка направления (реверса)
  - platform: fastled_clockless #Указание платформы подсветки
    chipset: WS2812B #Указание чипсета
    pin: GPIO12 #Инициализация порта
    num_leds: 8 #Количество светодиодов
    rgb_order: GRB #Указание цветовой схемы
    name: "led2" #Установка названия
    effects: #Создание эффектов
      - addressable_color_wipe:
          name: Red
          colors:
            - red: 100% #Установка цвета на 100%
              green: 0% #Установка цвета на 0%
              blue: 0% #Установка цвета на 0%
              num_leds: 1 #Указание с каким количество светодиодов работать
            - red: 0% #Установка цвета на 0%
              green: 0% #Установка цвета на 0%
              blue: 0% #Установка цвета на 0%
              num_leds: 1 #Указание с каким количество светодиодов работать
          add_led_interval: 100ms #Установка времени задержки
          reverse: False #Установка направления (реверса)
      - addressable_color_wipe:
          name: Green
          colors:
            - red: 0% #Установка цвета на 0% 
              green: 100% #Установка цвета на 100%
              blue: 0% #Установка цвета на 0% 
              num_leds: 1 #Указание с каким количество светодиодов работать
            - red: 0% #Установка цвета на 0%
              green: 0% #Установка цвета на 0%
              blue: 0% #Установка цвета на 0%
              num_leds: 1 #Указание с каким количество светодиодов работать
          add_led_interval: 100ms #Установка времени задержки
          reverse: False #Установка направления (реверса)
      - addressable_color_wipe:
          name: Blue
          colors: 
            - red: 0% #Установка цвета на 0%
              green: 0% #Установка цвета на 0%
              blue: 100% #Установка цвета на 100%
              num_leds: 1 #Указание с каким количество светодиодов работать
            - red: 0% #Установка цвета на 0%
              green: 0% #Установка цвета на 0%
              blue: 0% #Установка цвета на 0%
              num_leds: 1 #Указание с каким количество светодиодов работать
          add_led_interval: 100ms #Установка времени задержки
          reverse: False #Установка направления (реверса)

  - platform: fastled_clockless #Указание платформы подсветки
    chipset: WS2812B #Указание чипсета
    pin: GPIO14 #Инициализация порта
    num_leds: 8 #Количество светодиодов
    rgb_order: GRB #Указание цветовой схемы
    name: "led3" #Установка названия
    effects: #Создание эффектов
      - addressable_color_wipe:
          name: Red
          colors:
            - red: 100% #Установка цвета на 100%
              green: 0% #Установка цвета на 0%
              blue: 0% #Установка цвета на 0%
              num_leds: 1 #Указание с каким количество светодиодов работать
            - red: 0% #Установка цвета на 0%
              green: 0% #Установка цвета на 0%
              blue: 0% #Установка цвета на 0%
              num_leds: 1 #Указание с каким количество светодиодов работать
          add_led_interval: 100ms #Установка времени задержки
          reverse: False #Установка направления (реверса)
      - addressable_color_wipe:
          name: Green
          colors:
            - red: 0% #Установка цвета на 0% 
              green: 100% #Установка цвета на 100%
              blue: 0% #Установка цвета на 0% 
              num_leds: 1 #Указание с каким количество светодиодов работать
            - red: 0% #Установка цвета на 0%
              green: 0% #Установка цвета на 0%
              blue: 0% #Установка цвета на 0%
              num_leds: 1 #Указание с каким количество светодиодов работать
          add_led_interval: 100ms #Установка времени задержки
          reverse: False #Установка направления (реверса)
      - addressable_color_wipe:
          name: Blue
          colors: 
            - red: 0% #Установка цвета на 0%
              green: 0% #Установка цвета на 0%
              blue: 100% #Установка цвета на 100%
              num_leds: 1 #Указание с каким количество светодиодов работать
            - red: 0% #Установка цвета на 0%
              green: 0% #Установка цвета на 0%
              blue: 0% #Установка цвета на 0%
              num_leds: 1 #Указание с каким количество светодиодов работать
          add_led_interval: 100ms #Установка времени задержки
          reverse: False #Установка направления (реверса)