
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
#sensor: !include sensor.yaml
mqtt:
  sensor:
    - name: "dc_voltage1"
      state_topic: "python/DC_Voltage1"
      unit_of_measurement: "V"
    - name: "dc_voltage2"
      state_topic: "python/DC_Voltage2"
      unit_of_measurement: "V"
    - name: "dc_voltage3"
      state_topic: "python/DC_Voltage3"
      unit_of_measurement: "V"
    - name: "dc_humiditly1"
      state_topic: "python/DC_Humiditly1"
      unit_of_measurement: "%"
    - name: "dc_rms1"
      state_topic: "python/DC_Rms1"
      unit_of_measurement: "A"
    - name: "dc_rms2"
      state_topic: "python/DC_Rms2"
      unit_of_measurement: "A"
    - name: "dc_rms3"
      state_topic: "python/DC_Rms3"
      unit_of_measurement: "A"
    - name: "dc_active_power1"
      state_topic: "python/DC_Active_power1"
      unit_of_measurement: "%"
    - name: "dc_active_power2"
      state_topic: "python/DC_Active_power2"
      unit_of_measurement: "%"
    - name: "dc_active_power3"
      state_topic: "python/DC_Active_power3"
      unit_of_measurement: "%"
    - name: "hu_pressure1"
      state_topic: "python/HU_Pressure1"
      unit_of_measurement: "Bar"
    - name: "hu_pressure2"
      state_topic: "python/HU_Pressure2"
      unit_of_measurement: "Bar"
    - name: "hu_temperature1"
      state_topic: "python/HU_Temperature1"
      unit_of_measurement: "℃"
    - name: "hu_temperature2"
      state_topic: "python/HU_Temperature2"
      unit_of_measurement: "℃"
    - name: "hu_termal_energy"
      state_topic: "python/HU_Termal_energy"
      unit_of_measurement: "Гкал"
    - name: "hu_water"
      state_topic: "python/HU_Water"
      unit_of_measurement: "м³"
    - name: "year"
      state_topic: "python/year"
    - name: "Recycled_heat"
      state_topic: "python/Recycled_heat"
      unit_of_measurement: "TWh"
    - name: "Emissions"
      state_topic: "python/Emissions"
      unit_of_measurement: "MTco2"

climate:
  - platform: generic_thermostat
    name: Термостат
    heater: switch.2_switch_2
    target_sensor: sensor.tasmota2_bme280_temperature
