
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
#sensor: !include sensor.yaml
mqtt:
  sensor:
    - name: "dc_voltage1"
      state_topic: "python/DC_Voltage1"
      unit_of_measurement: "V"
    - name: "dc_voltage2"
      state_topic: "python/DC_Voltage2"
      unit_of_measurement: "V"
    - name: "dc_voltage3"
      state_topic: "python/DC_Voltage3"
      unit_of_measurement: "V"
    - name: "dc_humiditly1"
      state_topic: "python/DC_Humiditly1"
      unit_of_measurement: "%"
    - name: "dc_rms1"
      state_topic: "python/DC_Rms1"
      unit_of_measurement: "A"
    - name: "dc_rms2"
      state_topic: "python/DC_Rms2"
      unit_of_measurement: "A"
    - name: "dc_rms3"
      state_topic: "python/DC_Rms3"
      unit_of_measurement: "A"
    - name: "dc_active_power1"
      state_topic: "python/DC_Active_power1"
      unit_of_measurement: "%"
    - name: "dc_active_power2"
      state_topic: "python/DC_Active_power2"
      unit_of_measurement: "%"
    - name: "dc_active_power3"
      state_topic: "python/DC_Active_power3"
      unit_of_measurement: "%"
