
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
#sensor: !include sensor.yaml
mqtt:
  sensor:
    - name: "Voltage1"
      state_topic: "python/Voltage1"
      unit_of_measurement: "V"
    - name: "Voltage2"
      state_topic: "python/Voltage2"
      unit_of_measurement: "V"
    - name: "Voltage3"
      state_topic: "python/Voltage2"
      unit_of_measurement: "V"
